# Default values for .helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: e-chauffeur
image:
  repository: registry.gitlab.com/fabnum-minarm/e-chauffeur/driver
  tag: stable
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
env:
  API_URL: api.localhost
imageCredentials:
  name: e-chauffeur-driver
  registry: registry.gitlab.com
  username: user
  password: pass

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: driver.localhost
  issuer: letsencrypt-staging

resources:
  limits:
    cpu: 1000m
    memory: 2048Mi
  requests:
    cpu: 500m
    memory: 1024Mi

nodeSelector: {}

tolerations: []

affinity: {}
