# Default values for .helm-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: e-chauffeur
monitoring:
  dashboard:
    deploy: true
    sidecarLabel: grafana-dashboard
  alert:
    enabled: true
    minimumPod: 1
    labels:
      app: prometheus-operator
      release: prometheus
image:
  repository: registry.gitlab.com/fabnum-minarm/e-chauffeur/driver
  tag: stable
  pullPolicy: Always

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
env:
  API_URL: api.localhost
  VAPID_PUBLIC_KEY: vapid.localhost
imageCredentials:
  name: e-chauffeur-driver
  registry: registry.gitlab.com
  username: user
  password: pass

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: true
  host: driver.localhost
  issuer: self-signing

resources:
  limits:
    cpu: 500m
    memory: 1024Mi
  requests:
    cpu: 100m
    memory: 512Mi

nodeSelector: {}

tolerations: []

affinity: {}
