{{- $fullName := include ".helm-chart.fullname" . -}}
apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: {{ $fullName }}
spec:
  secretName: {{ $fullName }}-tls
  issuerRef:
    name: {{ .Values.ingress.issuer }}
  commonName: {{ .Values.ingress.host | quote }}
  dnsNames:
    - {{ .Values.ingress.host | quote }}
  acme:
    config:
      - http01:
          ingressClass: nginx
        domains:
          - {{ .Values.ingress.host | quote }}
